---
title: "Stat Consulting Project - Exploratory Analysis"
author: "Rosie Quint"
date: "2026-02-03"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(haven)
library(tidyverse)

all_data <- read_dta("ZZIR62FL.DTA")

# extract relevant variables
selected_data <- all_data %>%
  select(
    caseid, 
    v012, # age at questioning
    v505, # how many other wives 
    v632, # husband as contraception decision-maker: 1 = mainly respondent, 2 = mainly husband,partner, 3 = joint decision, 6 = other, 9 = missing
    v744a, v744b, v744c, v744d, v744e, # believes beating justified - different reasons
    v763a, # any STI last 12 months
    v812, v813, # presence of husband for wife-beating question / presence of other male
    v745a, v745b, # owns house alone/jointly, owns land alone/jointly 
    v508, # year of first cohabitation
    v822, # wife justified asking husband to use condom if he has STI
    v301, # knowledge of any method of contraception
    v474a, v474b, v474c, v474d, v474e, v474f, # knowldge about TB - spread by different methods
    v751, # ever heard of AIDS, couldn't find 751BP-WP
    v777,# shame about HIV (couldn't find 777a)
    v746 ) # earns more than husband: 1 = more than him, 2 = less, 3 = about the same, 4 = husband brings in no money, 8 = dont know, 9 = missing


# create man listening variable based on if either v812 (husband listening) or v813 (other man listening) is true 
selected_data <- selected_data %>%
  mutate(
    man_listening = factor(ifelse(v812 == 1 | v813 == 1 , 1, 0)), # 0 = no, 1 = yes - listening, 2 = not-listening, 9 = missing
    anybeating_justified = ifelse(v744a == 1 | v744b == 1 | v744c == 1 | v744d == 1 | v744e == 1, 1, 0),
    owns_house_or_land = ifelse(v745a == 1 | v745b == 1, 1, 0),
    age_first_cohab = v012 - (2015 - v508)
         )
```

Exploratory plots and descriptives
```{r}

# create histogram for number of other wives (v505)
ggplot(data = selected_data, aes(x = v505)) +
  geom_histogram(binwidth = 1) + # add title
  ggtitle("Distribution of Number of Co-Wives (v505)")

# same histogram with anomaly removed (v505 > 10)
ggplot(data = selected_data %>% filter(v505 <= 10), aes(x = v505)) +
  geom_histogram(binwidth = 1) + 
  ggtitle("Distribution of Number of Co-Wives (v505) with Anomalies Removed")

# plot husband as decision-maker
ggplot(data = selected_data, aes(x = v632)) +
  geom_bar() + 
  ggtitle("Husband as Contraception Decision-Maker (v632)") + #annotate what each number means
  scale_x_continuous(breaks = c(1,2,3,6,9),
                     labels = c("Mainly respondent", "Mainly husband/partner", "Joint decision", "Other", "Missing")) +  # turn labels 
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  ylab("Count")

```


Table 1 - variable summaries
```{r}
library(table1)

selected_data <- selected_data %>%
  mutate(
    ## demographics
    v012 = as.numeric(v012),   # age
    v505 = as.numeric(v505),   # number of co-wives
    age_first_cohab = as.numeric(age_first_cohab),   # year first cohabitation
    
    ## binary / categorical DHS variables → factors
    across(
      c(
        v632,      # husband decides contraception
        v744a, v744b, v744c, v744d, v744e,  # beating justified reasons
        v763a,     # STI last 12 months
        v812, v813,# presence during interview
        v745a, v745b, # house / land ownership
        v822,      # justified asking condom
        v301,      # knows contraception
        v474a, v474b, v474c, v474d, v474e, v474f, # TB knowledge items
        v751,      # ever heard of AIDS
        v777,       # shame about HIV
        anybeating_justified,
        man_listening,
        owns_house_or_land
      ),
      ~ factor(.)
    )
  )

label(selected_data$v012)  <- "Age at interview (years)"
label(selected_data$v505) <- "Number of co-wives"
label(selected_data$age_first_cohab) <- "Age at first cohabitation"

label(selected_data$v632) <- "Husband decides on contraception"

label(selected_data$v744a) <- "Beating justified: goes out without telling"
label(selected_data$v744b) <- "Beating justified: neglects children"
label(selected_data$v744c) <- "Beating justified: argues with husband"
label(selected_data$v744d) <- "Beating justified: refuses sex"
label(selected_data$v744e) <- "Beating justified: burns food"

label(selected_data$v763a) <- "Had STI in last 12 months"

label(selected_data$v812) <- "Husband present during interview"
label(selected_data$v813) <- "Other male present during interview"

label(selected_data$v745a) <- "Owns house"
label(selected_data$v745b) <- "Owns land"

label(selected_data$v822) <- "Justified asking condom if husband has STI"
label(selected_data$v301) <- "Knows any contraceptive method"


label(selected_data$v751) <- "Ever heard of AIDS"
label(selected_data$v777) <- "Feels shame if HIV positive"

label(selected_data$anybeating_justified) <- "YES to any wife beating justified questions"
label(selected_data$man_listening) <- "Any man listening"
label(selected_data$owns_house_or_land) <- "Owns house or land"
label(selected_data$age_first_cohab) <- "Age at first cohabitation"


table1(
  ~ v012 + v505 + age_first_cohab +
    v632 +
    v744a + v744b + v744c + v744d + v744e +
    v763a +
    v812 + v813 +
    v745a + v745b +
    v822 + v301 +
    v751 + v777 + 
    anybeating_justified + man_listening + owns_house_or_land + age_first_cohab,
  data = selected_data
)


# table 1 stratified by man listening status
# remove those with missing data for man_listening variable
selected_data_manlistening <- selected_data %>%
  filter(!is.na(man_listening), man_listening != 9)

table1(
  ~ v012 + v505 + age_first_cohab +
    v632 +
    v763a +
    v812 + v813 +
    v745a + v745b +
    v822 + v301 +
    v751 + v777 + anybeating_justified + owns_house_or_land + age_first_cohab | man_listening,
  data = selected_data_manlistening
)

```



Descriptives related to predictors in question 1-  violin plot for with man listening vs without 
```{r}
# plot number of other wives (v505) distribution by man_listening status
ggplot(data = selected_data_manlistening, aes(x = man_listening, y = v505)) +
  geom_violin()

```

Objective 2: protective factors 
Scatter plots 
```{r}
selected_data_protectivefactors <- selected_data %>%
  select(v746, owns_house_or_land, age_first_cohab, v822, v763a) %>% # remove na
  filter(!is.na(v746), !is.na(owns_house_or_land), !is.na(age_first_cohab), !is.na(v822), !is.na(v763a))

table1(
  ~ v746 + owns_house_or_land + age_first_cohab + v822 | v763a,
  data = selected_data_protectivefactors
)
```
Question 2 